### ISSUE TITLE
Default value :defaults is invalid for property destination

### ISSUE THREAD

**Issue by emachnic** [widgit-cookbooks/nxlog#18]
In preparation for Chef Client 13, I enabled `treat_deprecation_warnings_as_errors` in my Test Kitchen config. I'm using version 0.8.7 of this cookbook and received the following error:

```
[2017-02-08T08:35:43-08:00] ERROR: Default value :defaults is invalid for property destination of resource nxlog_source. In Chef 13 this will become an error: Option destination must be a kind of [String, Array]!  You passed :defaults.. (CHEF-5)C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/nxlog/resources/source.rb:30:in `class_from_file'.
       Please see https://docs.chef.io/deprecations_custom_resource_cleanups.html for further details and information on how to correct this problem. at C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/formatters/doc.rb:419:in `deprecation'

       ================================================================================
       Recipe Compile Error in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/nxlog/resources/source.rb
       ================================================================================

       Chef::Exceptions::DeprecatedFeatureError
       ----------------------------------------
       "Default value :defaults is invalid for property destination of resource nxlog_source. In Chef 13 this will become an error: Option destination must be a kind of [String, Array]!  You passed :defaults.. (CHEF-5)C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/nxlog/resources/source.rb:30:in `class_from_file'.\nPlease see https://docs.chef.io/deprecations_custom_resource_cleanups.html for further details and information on how to correct this problem. at C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/formatters/doc.rb:419:in `deprecation'"

       Platform:
       ---------
       x64-mingw32
```

This looks to be related to the code at line https://github.com/widgit-cookbooks/nxlog/blob/master/resources/source.rb#L30. According to the [Chef docs](https://docs.chef.io/deprecations_custom_resource_cleanups.html#invalid-defaults), this is because `:defaults` is not the same type of property that is being declared in the line. I believe that changing it to just an empty array `[]` or an empty string `''` should fix the warning.

**Comment by esalter** [comment]
Can this be fixed please?
